# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.config/zsh/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Used for setting user's interactive shell configuration and executing commands,
# will be read when starting as an interactive shell.

# User configuration
export HIST_STAMPS="dd/mm/yyyy"
export HISTFILE="${XDG_CACHE_HOME}/zsh/history"
setopt HIST_IGNORE_ALL_DUPS

# SSH agent
unset SSH_AGENT_PID
if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
    export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
fi

# Bash completion in zsh
# autoload bashcompinit
# bashcompinit -d "${XDG_CACHE_HOME}/bash"

###########
# Aliases #
###########

# Print the weather
wttr_weather () {
    if [ -z "${1}" ]
    then
        curl 'https://wttr.in/?m'
    else
        curl 'https://wttr.in/'"$(echo $1)"
    fi
}
# Show diff with color
diff-colorful () {
    diff "${1}" "${2}" --color=always --side-by-side | less -R
}
# Show default file picker
xdg-which-default () {
    type="$(xdg-mime query filetype "${1}")"
    xdg-mime query default "${type}"
}
# Colorful python
alias py='bpython'
# Make mutt like neomutt
alias mutt='neomutt'
# For archlinux, clean orphans
alias arch-killorphans='sudo pacman -Rns $(pacman -Qttdq)'
# Source anacondo
alias anaconda-source='source "${HOME}/Data/anaconda3/bin/activate"'

#######
# ZIM #
#######

# Download zimfw plugin manager if missing.
if [[ ! -e ${ZIM_HOME}/zimfw.zsh ]]; then
    curl -fsSL --create-dirs -o ${ZIM_HOME}/zimfw.zsh \
        https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh
fi

# Install missing modules, and update ${ZIM_HOME}/init.zsh if missing or outdated.
if [[ ! ${ZIM_HOME}/init.zsh -nt ${ZDOTDIR:-${HOME}}/.zimrc ]]; then
    source ${ZIM_HOME}/zimfw.zsh init -q
fi

# Set a custom path for the completion dump file.
zstyle ':zim:completion' dumpfile \
    "${XDG_CACHE_HOME}/zsh/zcompdump-${ZSH_VERSION}"
zstyle ':completion::complete:*' cache-path \
    "${XDG_CACHE_HOME}/zsh/zcompcache-${ZSH_VERSION}"

# Source and initialize zim modules
source ${ZIM_HOME}/init.zsh

# Set editor default keymap to emacs (`-e`) or vi (`-v`)
bindkey -v

# Bind ^[[A/^[[B manually so up/down works both before and after zle-line-init
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
# Bind up and down keys
zmodload -F zsh/terminfo +p:terminfo
if [[ -n ${terminfo[kcuu1]} && -n ${terminfo[kcud1]} ]]; then
    bindkey ${terminfo[kcuu1]} history-substring-search-up
    bindkey ${terminfo[kcud1]} history-substring-search-down
fi
bindkey '^P' history-substring-search-up
bindkey '^N' history-substring-search-down
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down

# Prompt

# If not in tty console; deload the spaceship theme and load p10k
# prompt default
# [[ ! -f ~/.config/zsh/.p10k.zsh ]] || source ~/.config/zsh/.p10k.zsh

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.config/zsh/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
# if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
#     source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
# fi

# To customize prompt, run `p10k configure` or edit ~/.config/zsh/.p10k.zsh.
[[ ! -f ~/.config/zsh/.p10k.zsh ]] || source ~/.config/zsh/.p10k.zsh
