#!/bin/sh

# Define our XDG Base Directories
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_DATA_HOME="${HOME}/Data/share"
export XDG_STATE_HOME="${HOME}/Data/state"

# Import Path
[ -d "${HOME}/.local/bin" ] && PATH="${HOME}/.local/bin:${PATH}"

# Load profiles from /etc/profile.d
if test -d "${XDG_CONFIG_HOME}/profile.d/"; then
    for profile in "${XDG_CONFIG_HOME}/profile.d/"*.sh; do
        test -r "$profile" && . "$profile"
    done
    unset profile
fi
